### ISSUE TITLE
Whitespace in tags?

### ISSUE THREAD

**Issue by remorse** [lokku/Text-Hogan#1]
Hi! I've left an issue on the Mustache spec to clarify, but I think there may be an error in handling whitespace within a tag. For example:

```
"{{#foo}}Don't render me{{/foo}}" "{{ #foo }}Don't render me{{ /foo }}"
```

with the data `{ foo => 0 }`, I would expect to get:

```
"" ""
```

Instead, I get:

```
"" "Don't render me"
```

Thanks,
Ricky

**Comment by kaoru** [comment]
Hi @remorse 

According to the Mustache Spec:

>   These tags' content MUST be a non-whitespace character sequence NOT
>   containing the current closing delimiter; each Section tag MUST be followed
>   by an End Section tag with the same content within the same section.

https://github.com/mustache/spec/blob/master/specs/sections.yml

I'm afraid it looks like this is the correct behaviour.

**Comment by remorse** [comment]
I'm arguing that. Mustache.js doesn't enforce this, and they even have a test at the end of the file ("Padding") that is obviously breaking that. (I think we're both commenting on both threads about this.)

**Comment by kaoru** [comment]
We are both commenting on both threads :-P Hopefully somebody from the Mustache team will comment.

**Comment by kaoru** [comment]
One thought: does it currently work if you put white-space into your custom tag declarations? For your case:

```
<?m #something ?>
```

You could have the opening tag set to "`<?m`" and your closing tag set to "`?>`"?

**Comment by remorse** [comment]
Hi! The only ways that I see to change the delimiters are either in the template or in the options passed to the compile function (and then down to scan). This doesn't allow me to specify opening vs closing, so I can't specify where the whitespace is...

**Comment by remorse** [comment]
OK, since the spec people aren't being very responsive, do you know where I would need to look to add this as a feature? I can import the module into my own namespace and make the change, and use that, but the code style (probably because it's a translation from JavaScript) is currently opaque.

Thanks,
Ricky

**Comment by remorse** [comment]
Hi! I found it. It's just been a long while since I've dealt with tokenizers like this.

Do you want me to submit a pull request with the change I'm making? I realize it would not match hogan.js anymore, so maybe it's not a good idea, but I could make it only work if a package variable is set.

Thanks,
Ricky

**Comment by kaoru** [comment]
Hi @remorse, sorry for the slow reply this week., I was a bit busy with `$work` :-)

Sending a pull request would be great. Adding a test would be better. Tying it to an optional parameter (like the `numeric_string_as_string` added already in the [1.01 release](https://metacpan.org/pod/Text::Hogan::Compiler#generate)) would be best.

Thanks!

**Comment by remorse** [comment]
Pull request sent in as #2. Closing this issue.
