### ISSUE TITLE
Please tag CPAN releases in git

### ISSUE THREAD

**Issue by jonassmedegaard** [lokku/Text-Hogan#5]
Hi,

Please git-tag your CPAN releases: That eases maintenance of downstream distribution packages (e.g. for Debian where I right now am looking into packaging Text::Hogan as it is needed for recent releases of Catmandu).

 - Jonas

**Comment by kaoru** [comment]
Hi Jonas,

No problem, do you have any preference for the type and format of the git tags?

* Annotated vs non-annotated?
* "v1.04" vs "1.04" vs something else?

My preference is for non-annotated tags and "v1.04"-style names.

**Comment by jonassmedegaard** [comment]
Quoting Alex Balhatchet (2016-12-28 10:57:25)
> No problem, do you have any preference for the type and format of the git tags?
> 
> * Annotated vs non-annotated?
> * "v1.04" vs "1.04" vs something else?
> 
> My preference is for non-annotated tags and "v1.04"-style names.

Nope, no preference - use whatever you prefer :-)

Thanks!

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by kaoru** [comment]
@jonassmedegaard tagged :)

`$ git log --oneline --decorate Changes`

* baa40e4 (HEAD -> master, tag: v1.04, origin/master, origin/HEAD) Version 1.04
* 2da0fcb (tag: v1.03) Update Changes file and bump version
* 0088d99 Update Changes file
* e18051b (tag: v1.02) bump version number, add documentation
* f9abf8b (tag: v1.01) Version 1.01
* a850440 (tag: v1.00) Version 1.00 - we now pass the whole mustache spec!
* ea75d13 (tag: v0.09) Version 0.09
* 1ab5129 (tag: v0.08) Version 0.08
* 89b7f66 (tag: v0.07) Version 0.07
* 1a214ac (tag: v0.06) Version 0.06
* b5dfb13 (tag: v0.05) Version 0.05
* 9e8f296 (tag: v0.04) Version 0.04
* 51fd4b3 (tag: v0.03) Version 0.03
* 460fde8 (tag: v0.02) Version 0.02
* fa6d6c8 (tag: v0.01) Get ready for release - docs, dist.ini, changes, etc.

**Comment by jonassmedegaard** [comment]
Thanks!

Please tag newer releases as well - seems 3 tags are missing :-)

**Comment by kaoru** [comment]
@jonassmedegaard done! And added 226ae1a which should mean that tags are automatically added from now on. The v1.08 tag was added automatically by me running `dzil release` :tada:

**Comment by jonassmedegaard** [comment]
Quoting Alex Balhatchet (2019-02-23 19:57:44)
> @jonassmedegaard done! And added 226ae1a which should mean that tags are automatically added from now on. The v1.08 tag was added automatically by me running `dzil release` :tada: 

Thanks :-)

v1.07 (or possibly v1.08) will be part of upcoming Debian release 
"Buster": https://tracker.debian.org/pkg/libtext-hogan-perl

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by kaoru** [comment]
Oooh that's great, big fan of Debian, I ran it for years at Nestoria which is also where we wrote Text:Hogan :)

**Comment by kaoru** [comment]
1.09 might be coming soon by the way, about to merge #9 I think :smile:
